### ISSUE TITLE
To-Do List 4/22 - 4/29

### ISSUE THREAD

**Issue by TJ-Butler** [PSUGraphicDesign/colevity#8]
- [ ] Finalize Wireframes and upload pdf by end of friday 4/24
- [ ] Slack / Google Hangouts meeting Saturday 4/25 @ 11 AM to discuss wireframes
- [ ] Review preliminary site designs Monday 4/27 in class
- [ ] Use in-class time to refine designs and select two options for Cami
